apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: springdeployments.boring.demo.org
spec:
  group: boring.demo.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: (Required) Name of the deployment.
                namespace:
                  type: string
                  description: Namespace to deploy app to. By default, this CR's namespace.
                replicas:
                  type: integer
                  description: Number of replica pods.
                image:
                  type: string
                  description: Full name for the deployment image.
          required:
            - name
  scope: Namespaced
  names:
    plural: springdeployments
    singular: springdeployment
    kind: SpringDeployment
    shortNames:
      - sd
      - sds
